In [1]:
import torch


x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
print(x.shape)

torch.Size([2, 5])


In [6]:
y = torch.rand([2,5])
y

tensor([[0.7615, 0.1286, 0.5846, 0.2341, 0.0614],
        [0.3177, 0.9967, 0.1409, 0.0058, 0.6562]])

In [7]:
y.view([1, 10])

tensor([[0.7615, 0.1286, 0.5846, 0.2341, 0.0614, 0.3177, 0.9967, 0.1409, 0.0058,
         0.6562]])

In [8]:
y = y.view([1,10])
print(y.shape)

torch.Size([1, 10])
